require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.colorscheme'
require 'user.telescope'
require 'user.treesitter'
require 'user.lualine'
require 'user.autopairs'
require 'user.cmp'
require 'user.lsp'
require 'user.impatient'
require 'user.scroll'

vim.cmd 'source ~/.config/nvim/core/rgconfig.vim'
-- legacy plugin configs
vim.cmd 'source ~/.config/nvim/core/plugconf.vim'
